---

# ============================================================================
# File  : .vintrc
# Author: Faris Chugthai
# Description: Linter for vimscript. Written in python
# Last Modified: Aug 25, 2019
# ============================================================================

# Vint follows yaml formatting so no more " comments

cmdargs:
    # Checking more strictly
    severity: style_problem
    # Enable coloring
    color: true

env:
    # Enable Neovim syntax
    neovim: true

policies:
    ProhibitImplicitScopeVariable:
        enabled: true
    ProhibitAbbreviationOption:
        enabled: true
    ProhibitSetNoCompatible:
        enabled: false
    # gonna set some newly discovered checks to true
    ProhibitUnnecessaryDoubleQuote:
        enabled: true
    ProhibitEqualTildeOperator:
        enabled: true
    ProhibitNoAbortFunction:
        enabled: true
    ProhibitUnusedVariable:
      enabled: false
    ProhibitInvalidMapCall:
      enabled: true

# fyi
# $: vint -V init.vim
# vint DEBUG: checking: `init.vim`
# vint DEBUG: severity: STYLE_PROBLEM
# vint DEBUG: enabled: ProhibitAbbreviationOption
# vint DEBUG: enabled: ProhibitAutocmdWithNoGroup
# vint DEBUG: enabled: ProhibitCommandRelyOnUser
# vint DEBUG: enabled: ProhibitCommandWithUnintendedSideEffect
# vint DEBUG: enabled: ProhibitEncodingOptionAfterScriptEncoding
# vint DEBUG: enabled: ProhibitEqualTildeOperator
# vint DEBUG: enabled: ProhibitImplicitScopeBuiltinVariable
# vint DEBUG: disabled: ProhibitImplicitScopeVariable
# vint DEBUG: enabled: ProhibitInvalidMapCall
# vint DEBUG: enabled: ProhibitMissingScriptEncoding
# vint DEBUG: enabled: ProhibitNoAbortFunction
# vint DEBUG: disabled: ProhibitSetNoCompatible
# vint DEBUG: enabled: ProhibitUnnecessaryDoubleQuote
# vint DEBUG: disabled: ProhibitUnusedVariable
# vint DEBUG: enabled: ProhibitUsingUndeclaredVariable

...
