# ============================================================================
# File  : .vintrc
# Author: Faris Chugthai
# Description: Linter for vimscript. Written in python
# Last Modified: Aug 25, 2019
# ============================================================================

# Vint follows yaml formatting so no more " comments

cmdargs:
    # Checking more strictly
    severity: style_problem
    # Enable coloring
    color: true

env:
    # Enable Neovim syntax
    neovim: true

policies:
    # ProhibitImplicitScopeVariable:
    #     enabled: false
    # ProhibitAbbreviationOption:
    #     enabled: false
    ProhibitSetNoCompatible:
        enabled: false
    # gonna set some newly discovered checks to true
    ProhibitUnnecessaryDoubleQuote:
        enabled: true
    ProhibitEqualTildeOperator:
        enabled: true
    ProhibitNoAbortFunction:
        enabled: true
